version: '2.4'
services:
     
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=rouk
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | timeout 2 nc -w 2 localhost 2181 | grep imok" ]
      interval: 5s
      timeout: 5s
      retries: 15      

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "kompost:1:1"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic kompost --describe" ]
      interval: 5s
      timeout: 5s
      retries: 15
    depends_on:
      zookeeper:
        condition: service_healthy